export { default as Card } from './CardFooter.vue'
export { default as CardContent } from './CardFooter.vue'
export { default as CardDescription } from './CardFooter.vue'
export { default as CardFooter } from './CardFooter.vue'
export { default as CardHeader } from './CardFooter.vue'
export { default as CardTitle } from './CardFooter.vue'